---
# Bad ansible! This playbook is an example of poor/bad practices!
# Bad practices may include:
#
#   Poor formatting and structure
#   Poor use of YAML - but good enough to parse
#   Inconsistent style
#   Incorrect use of modules
#   Poor module choice
#   Unclear names
#   Hard coding / poor use of variables
#   Roles - what are roles?
#   Bare variables
#   No use of handlers

- name: Deploy the application through roles
  vars:
  hosts: all
  become: True

- roles:
    - { role: reposetup }
    - { role: postgressdeploy, when: {{ inventory_host }} is in {{ appdbs }} }
    - { role: tomcatsetup, when: {{ inventory_host }} is in {{ apps }} }
    - { role: haproxy, when: {{ inventory_host }} is in {{ frontends }} }
    - { role: httpdsetup, when: {{ inventory_host }} is in {{ frontends }} }
