- name: Postgres Deployed
  yum:
    pkg: postgresql-server
    state: latest
- name: Postgres started
  service:
    name: postgresql
    enabled: yes
    state: started
- name: Postgres Database Initialized
  postgresql_db:
    name: acme
    state: present
    encoding: UTF-8
  # make sure psycop2 module is insalled on this host.
