- name: Deploy HAProxy
  yum:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - HAProxy 
    - httpdie
- name: enable HAProxy
  service:
    haproxy:
    state: started
- name: Configure HAProxy
  template:
    src: templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart HAProxy
  