- name: Tomcat installed
  yum:
    pkg: tomcat
    state: present
- name: Tamcat Service Started
  service:
    name: tomcat
    enabled: True
    state: started

- name: Tomcat Directory Created
  file:
    path: /usr/share/tomcat/webapps/ROOT
    state: directory

- name: Tomcat copy static index.html to tomcat webapps/ROOT/index.html
  template:
    src: templates/index.html.j2
    dest: /usr/share/tomcat/webapps/ROOT/index.html
    mode: 0644
  notify: restart tomcat

